# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_YpKZjSgd8j6A8aBy1i22xWrOFhZPVNl
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv('network_traffic.csv')
print(df.head())

import pandas as pd

df = pd.read_csv('network_traffic.csv')
print(df.head())

print(df.info())
print(df.describe())

print(df['flag'].value_counts())

df['timestamp'] = pd.to_datetime(df['timestamp'])
print(df.dtypes)

print(f"Start time: {df['timestamp'].min()}")
print(f"End time: {df['timestamp'].max()}")

print(df.groupby('protocol')['packet_size'].mean())

suspicious_df = df[df['flag'] == 'suspicious']
print(suspicious_df)

print("Unique source IPs:", df['source_ip'].unique())
print("Unique destination IPs:", df['dest_ip'].unique())

print(df.nlargest(3, 'packet_size'))

large_packets = df[df['packet_size'] > 10000]
print(large_packets)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv('network_traffic.csv')

# Convert timestamp to datetime
df['timestamp'] = pd.to_datetime(df['timestamp'])

sns.countplot(x='flag', data=df)
plt.title('Normal vs Suspicious Traffic Counts')
plt.show()

sns.histplot(df['packet_size'], bins=10, kde=True)
plt.title('Packet Size Distribution')
plt.xlabel('Packet Size (bytes)')
plt.show()

plt.figure(figsize=(10, 5))
sns.lineplot(x='timestamp', y='packet_size', hue='flag', data=df, marker='o')
plt.title('Packet Size Over Time')
plt.xlabel('Timestamp')
plt.ylabel('Packet Size (bytes)')
plt.xticks(rotation=45)
plt.show()